baseurl = "/"
title = "Rikke Barsten"
theme = "hugo-theme-cleanwhite"
languageCode = "en-us"
# Enable comments by entering your Disqus shortname
disqusShortname = "rikkebarsten"
googleAnalytics = ""
preserveTaxonomyNames = true
paginate = 5 #frontpage pagination

ignoreFiles = ["\\.Rmd$", "\\.Rmarkdown$", "_files$", "_cache$"]

[outputs]
home = ["HTML", "RSS"]

[params]
  header_image = "img/kaerehave2.jpg"
  #SEOTitle = ""
  #description = ""
  #keyword = ""
  slogan = "Exploring, analyzing and visualizing data"

  image_404 = "img/404-bg.jpg"
  title_404 = "Sorry, but the page you requested does not seem to exist."

  # leancloud storage for page view counter
  page_view_conter = false 
  leancloud_app_id = ""
  leancloud_app_key = ""

  # algolia site search
  algolia_search = false
  #algolia_appId = ""
  #algolia_indexName = ""
  #algolia_apiKey = ""

  # Sidebar settings
  sidebar_about_description = "Data analyst and open data enthusiast"
  sidebar_avatar = "img/rikkebarsten.jpg"      # use absolute URL, seeing it's used in both `/` and `/about/`
  gravatarEmail = "rikkebarsten@gmail.com"
  
  featured_tags = true 
  featured_condition_size = 1 



  #friends = true
  bookmarks = false
  about_me = true

  [params.social]
  rss            = false 
  email          = "rikkebarsten@gmail.com"
  #facebook      = "full profile url in facebook"
  #googleplus    = "full profile url in googleplus"
  #twitter       = "full profile url in twitter"
  linkedin       = "https://www.linkedin.com/in/rikke-barsten-2a038083/"
  stackoverflow  = "https://stackoverflow.com/users/4792734"
  #instagram     = "full profile url in instagram"
  github         = "https://github.com/RikkeBarsten"
  #wechat         = "your wechat qr code image"
  #medium         = "full profile url in medium"
  #pinterest     = "full profile url in pinterest"
  
  #[[params.friend_link]]
  #title = "Linda的博客"
  #href =  "https://zhaozhihan.com"

  #[[params.bookmark_link]]
  #title =  "Martin Fowler"
  #href =  "https://martinfowler.com"
  #[[params.bookmark_link]]
  #title = "ServiceMesher"
  #href =  "http://www.servicemesher.com"

  
  #[[params.addtional_menus]]
  #title =  "BOOKS"
  #href =  "/top/books/"
  [[params.addtional_menus]]
  title =  "ABOUT"
  href =  "/top/about/"

