---
title: Lego themes and sets - part two
subtitle: Building a dendrogram
author: Rikke Barsten
date: '2019-01-19'
slug: lego-themes-and-sets-part-two
categories: []
tags: [R, d3, javascript, dendrogram, visualization, lego]
showtoc: FALSE
---
In the previous post I output a dendrogram using the networkD3 R package. In this post, I use D3 directly to make a nicely formatted and customized version of this dendrogram.

D3 can take many data format as input, but since my lego data is already in hierarchical format, it is easy to use the rjson library to convert it to a JSON object: 

```{r eval=FALSE}
library(rjson)

star_wars_json <- toJSON(ToListExplicit(star_wars, unname=TRUE))
write(star_wars_json, "/data/star_wars.json")

```

The javascript code creating the visualization is at the end of the post, but here's the resulting visualization of the Star Wars subtree:

<svg width="800" height="7400"></svg>
<script src="https://d3js.org/d3.v5.min.js"></script>      


In this dendrogram vizualization I can control all parts of the output; colors, fonts, sizes, positioning and so forth. I borrowed the basic code for making the dendrogram from one of [Mike Bostocks ObservableHQ notebooks](https://beta.observablehq.com/@mbostock/d3-cluster-dendrogram), and made some adjustments. One of them is to add the release year to the sets ind the dendrogram. I do this by testing if a node has children. If not, it's a set, and then I add the year.

This visualization is only a small part (735 out of 14974 nodes) of the original dataset. To be able to display all the data, I will need a dynamic and interactive visualization, that can zoom in on parts of the dataset. In the next post or two, I will try to make some examples of this, also using the d3 library.


Heres the code outputting the dendrogram:
```{js}

var svg = d3.select("svg"),
margin = {top: 5, right: 270, bottom: 5, left: 5},
width = +svg.attr("width") - margin.left - margin.right,
height = +svg.attr("height") - margin.top - margin.bottom;



d3.json("/data/star_wars.json").then(function(data) {
 

  const root = d3.hierarchy(data)
    .sort((a, b) => (a.height - b.height) || a.data.name.localeCompare(b.data.name));
    root.dx = 10;
    root.dy = width / (root.height + 1);
  


  d3.cluster().nodeSize([root.dx, root.dy])(root);

  let x0 = Infinity;
  let x1 = -x0;
  root.each(d => {
    if (d.x > x1) x1 = d.x;
    if (d.x < x0) x0 = d.x;
  });

 
    var g = svg.append("g")
      .attr("font-family", "sans-serif")
      .attr("font-size", 10)
      .attr("transform", `translate(${root.dy / 3},${root.dx - x0})`);


  var link = g.append("g")
    .attr("fill", "none")
    .attr("stroke", "#555")
    .attr("stroke-opacity", 0.4)
    .attr("stroke-width", 1.5)
  .selectAll("path")
    .data(root.links())
    .enter().append("path")
      .attr("d", d => 
        `M${d.target.y},${d.target.x}
        C${d.source.y + root.dy / 2},${d.target.x}
         ${d.source.y + root.dy / 2},${d.source.x}
         ${d.source.y},${d.source.x}
      `);


  var node = g.append("g")
      .attr("stroke-linejoin", "round")
      .attr("stroke-width", 3)
    .selectAll("g")
    .data(root.descendants().reverse())
    .enter().append("g")
      .attr("transform", d => `translate(${d.y},${d.x})`);

  node.append("circle")
      .attr("fill", d => d.children ? "#555" : "#999")
      .attr("r", 2.5);

  node.append("text")
      .attr("dy", "0.31em")
      .attr("x", d => d.children ? -3 : 6)
      .text(d =>  d.children ? d.data.name : d.data.name + " - " + d.data.year)
    .filter(d => d.children)
      .attr("text-anchor", "end")
    .clone(true).lower()
      .attr("stroke", "white");

});

```
Since R markdown does not output [template literals](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Template_literals) well, the code is not nicely formatted, but this doesn't affect the code execution.
